public class strings {

    String[] motivationalquotes={"Act as if what you do makes a difference. It does.",
            "Success is not final, failure is not fatal: it is the courage to continue that counts.",
            "Never bend your head. Always hold it high. Look the world straight in the eye.",
            "What you get by achieving your goals is not as important as what you become by achieving your goals.",
            "Believe you can and you're halfway there.",
            "When you have a dream, you've got to grab it and never let go.",
            "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
            "No matter what you're going through, there's a light at the end of the tunnel.",
            "It is our attitude at the beginning of a difficult task which, more than anything else, will affect its successful outcome.",
            "Life is like riding a bicycle. To keep your balance, you must keep moving.",
            "Just don't give up trying to do what you really want to do. Where there is love and inspiration, I don't think you can go wrong.",
            "Limit your \"always\" and your \"nevers.\"",
            "Nothing is impossible. The word itself says \"I'm possible!\"",
            "You are never too old to set another goal or to dream a new dream.",
            "Try to be a rainbow in someone else's cloud.",
            "You do not find the happy life. You make it.",
            "Inspiration comes from within yourself. One has to be positive. When you're positive, good things happen.",
            "Sometimes you will never know the value of a moment, until it becomes a memory.",
            "The most wasted of days is one without laughter.",
            "You must do the things you think you cannot do.",
            "It isn't where you came from. It's where you're going that counts.",
            "It is never too late to be what you might have been.",
            "Stay close to anything that makes you glad you are alive.",
            "You get what you give.",
            "Some people look for a beautiful place. Others make a place beautiful.",
            "Happiness often sneaks in through a door you didn't know you left open.",
            "We must be willing to let go of the life we planned so as to have the life that is waiting for us.",
            "Happiness is not by chance, but by choice.",
            "Life changes very quickly, in a very positive way, if you let it.",
            "Keep your face to the sunshine and you cannot see a shadow.",
            "Never limit yourself because of others’ limited imagination; never limit others because of your own limited imagination.",
            "Be the change that you wish to see in the world.",
            "Let us make our future now, and let us make our dreams tomorrow's reality.",
            "You don't always need a plan. Sometimes you just need to breathe, trust, let go, and see what happens.",
            "If I cannot do great things, I can do small things in a great way.",
            "My mission in life is not merely to survive, but to thrive.",
            "You are enough just as you are.",
            "The bad news is time flies. The good news is you're the pilot.",
            "Spread love everywhere you go.",
            "Don't wait. The time will never be just right.",
            "Life has got all those twists and turns. You've got to hold on tight and off you go.",
            "If you look at what you have in life, you'll always have more.",
            "Inspiration is some mysterious blessing which happens when the wheels are turning smoothly.",
            "With the right kind of coaching and determination you can accomplish anything.",
            "If you have good thoughts they will shine out of your face like sunbeams and you will always look lovely.",
            "No matter what people tell you, words and ideas can change the world.",
            "Each person must live their life as a model for others.",
            "A champion is defined not by their wins but by how they can recover when they fall.",
            "Motivation comes from working on things we care about.",
            "Keep your face always toward the sunshine, and shadows will fall behind you."


    };
    String[] familyquotes={"I sustain myself with the love of family.",
            "Happiness is having a large, loving, caring, close-knit family in another city.",
            "All happy families are alike; each unhappy family is unhappy in its own way.",
            "A dysfunctional family is any family with more than one person in it.",
            "My mother used to tell me that when push comes to shove, you always know who to turn to. That being a family isn't a social construct but an instinct.",
            "What can you do to promote world peace? Go home and love your family.",
            "Home is where you are loved the most and act the worst.",
            "So much of what is best in us is bound up in our love of family, that it remains the measure of our stability because it measures our sense of loyalty.",
            "You are born into your family and your family is born into you. No returns. No exchanges.",
            "There is no doubt that it is around the family and the home that all the greatest virtues, the most dominating virtues of human, are created, strengthened and maintained.",
            "In truth a family is what you make it. It is made strong, not by number of heads counted at the dinner table, but by the rituals you help family members create, by the memories you share, by the commitment of time, caring, and love you show to one another, and by the hopes for the future you have as individuals and as a unit.",
            "The world, we'd discovered, doesn't love you like your family loves you.",
            "A family is one of nature's solubles; it dissolves in time like salt in rainwater.",
            "Our most basic instinct is not for survival but for family.",
            "When all the dust is settled and all the crowds are gone, the things that matter are faith, family, and friends.",
            "In every conceivable manner, the family is a link to our past, bridge to our future.",
            "A family doesn't have to perfect; it just needs to be united.",
            "Everyone needs a house to live in, but a supportive family is what builds a home.",
            "Everyone needs a house to live in, but a supportive family is what builds a home.",
            "Family is the most important thing in the world.",
            "Families are the compass that guides us. They are the inspiration to reach great heights, and our comfort when we occasionally falter.",
            "My greatest pleasure is spending time with my family.",
            "A man travels the world over in search of what he needs, and returns home to find it.",
            "Family is a life jacket in the stormy sea of life.",
            "The only rock I know that stays steady, the only institution I know that works, is the family.",
            "There's only one thing more precious than our time and that's what we spend it on.",
            "Home should be an anchor, a port in a storm, a refuge, a happy place in which to dwell, a place where we are loved and where we can love.",
            "Families are like branches on a tree. We grow in different directions yet our roots remain as one.",
            "The greatest moments in life are not concerned with selfish achievements but rather with the things we do for the people we love and esteem.",
            "Family and friends are hidden treasures, seek them and enjoy their riches.",
            "Other things may change us, but we start and end with the family.",
            "You don't choose your family. They are God's gift to you, as you are to them.",
            "A happy family is but an earlier heaven.",
            "Sticking with your family is what makes it a family.",
            "Ohana means family. Family means no one gets left behind or forgotten.",
            "The family is one of nature's masterpieces.",
            "Having somewhere to go is home. Having someone to love is family. Having both is a blessing.",
            "Family: where life begins and love never ends.",
            "Being a family means you are a part of something very wonderful. It means you will love and be loved for the rest of your life.",
            "The bond that links your true family is not one of blood, but of respect and joy in each other's life.",
            "Family is not an important thing. It's everything.",
            "Peace is the beauty of life. It is sunshine. It is the smile of a child, the love of a mother, the joy of a father, the togetherness of a family. It is the advancement of man, the victory of just cause, the triumph of truth.",


    };
    String[] funquote={"The sea, once it casts its spell, holds one in its net of wonder forever.",
            "Because there’s nothing more beautiful than the way the ocean refuses to stop kissing the shoreline, no matter how many times it’s sent away.",
            "To escape and sit quietly on the beach — that’s my idea of paradise.",
            "I followed my heart, and it led me to the beach.",
            "I love the beach. I love the sea. All my life I live within — in front of the sea.",
            "There’s no place like home except for the beach.",
            "Why do we love the sea? It is because it has some potent power to make us think things we like to think.",
            "On the beach, you can live in bliss.",
            "Adults are just outdated children.",
            "Hugs can do great amounts of good, especially for children.",
            "There can be no keener revelation of a society’s soul than the way in which it treats its children.",
            "If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.",
            "Children have one kind of silliness, as you know, and grown-ups have another kind.",
            "The soul is healed by being with children.",


    };
    String[] motherquote={"Children are the anchors of a mother's life.",
            "There is an endearing tenderness in the love of a mother to a son that transcends all other affections of the heart.",
            "Men are what their mothers made them.",
            "There has never been, nor will there ever be, anything quite so special as the love between the mother and a son",
            "Child's best friend is his mother.",
            "Moms are as relentless as the tides. They don't just drive us to practice, they drive us to greatness.",
            "All I am I owe to my mother.",
            "All women become like their mothers. That is their tragedy. No man does. That’s his.",
            "If love is as sweet as a flower, then my mother is that sweet flower of love.",
            "A mother’s love doesn’t make her son more dependent and timid; it actually makes him stronger and more independent.",
            "To a mother, a son is never a fully grown man; and a son is never a fully grown man until he understands and accepts this about his mother.",
            "A mother’s arms are made of tenderness and children sleep soundly in them.",
            "A man never sees all that his mother has been to him until it's too late to let her know that he sees it.",
            "The most important mark I will leave on this world is my son.",
            "Mothers are inscrutable beings to their sons, always.",
            "My mother is my root, my foundation. She planted the seed that I base my life on, and that is the belief that the ability to achieve starts in your mind.",
            "The heart of a mother is a deep abyss at the bottom of which you will always find forgiveness.",
            "Mother is her son's first god; she must teach him the most important lesson of all — how to love",
            "If love is as sweet as a flower, then my mother is that sweet flower of love.",
            "A mother is she who can take the place of all others but whose place no one else can take.",
            "A man loves his sweetheart the most, his wife the best, but his mother the longest.",
            "Life began with waking up and loving my mother's face.",
            "We are born of love; Love is our mother.",
            "My mother was my role model before I even knew what that word was.",
            "Sometimes the strength of motherhood is greater than natural laws.",
            "There’s no way to be a perfect mother, and a million ways to be a good one.",
            "Motherhood is the biggest gamble in the world. It is the glorious life force. It’s huge and scary — it’s an act of infinite optimism.",
            "I can imagine no heroism greater than motherhood.",
            "A mother is the one who fills your heart in the first place",
            "The natural state of motherhood is unselfishness.",
            "Life doesn't come with a manual. It comes with a mother",
            "My mom is definitely my rock.",
            "A mother's love endures through all.",
            "All I am I owe to my mother.",
            "God could not be everywhere, and therefore he made mothers.",
            "The influence of a mother in the lives of her children is beyond calculation.",
            "When you look into your mother's eyes, you know that is the purest love you can find.",
            "Motherhood: All love begins and ends there.",
            "Most mothers are instinctive philosophers.",
            "A mother understands what a child does not say.",
            "Mothers don't sleep. They just worry with their eyes closed.",
            "Sooner or later, we all quote our mothers.",
            "A mother is your first friend, your best friend, your forever friend.",
            "Nothing is really lost until your mom can't find it.",
            "A mother's arms are more comforting than anyone else's.",
            "Moms are like buttons — they hold everything together.",
            "I can only hope to be 10% of the mom mine was to me.",
            "A mother's hug lasts long after she lets go.",

    };
    String[] lazyqquotes={"The best thing to do first thing in the morning is to go right back to sleep.",
            "Sleep is the best meditation.",
            "Learn from yesterday, live for today, look to tomorrow, rest this afternoon.",
            "Don’t give up on your dreams. Keep sleeping.",
            "There is no sunrise so beautiful that it is worth waking me up to see it.",
            "\"Go to bed you’ll feel better tomorrow\" is the human version of \"Did you try turning it off and on again?\"",
            "A good laugh and a long sleep are the two best cures for anything.",
            "You miss 100% of the naps you don’t take",
            "I love sleep because it’s like a time machine to breakfast.",
            "Let’s start by taking a smallish nap or two …",
            "I love sleep. My life has the tendency to fall apart when I'm awake, you know?",
            "I usually take a two-hour nap from one to four.",
            "Laugh and the world laughs with you. Snore and you sleep alone",
            "When the going gets tough, the tough take a nap.",
            "I don't feel old. I don't feel anything till noon. That's when it's time for my nap.",
            "The nicest thing for me is sleep. Then at least I can dream.",
            "When I wake up, I am reborn.",
            "There is a time for many words, and there is also a time for sleep.",
            "We are such stuff as dreams are made on.",
            "You know you're in love when you can't fall asleep because reality is finally better than your dreams."

    };
}
